### ISSUE TITLE
Accurate test timing

### ISSUE THREAD

**Issue by moonwatcher** [emusolutions/LAGraph#18]
Once we have an implementation that correctly computes the start and end clock cycle of a test for LucataGraphBLAS, we should port the same logic to LAGraph. See [issue 294](https://github.com/emusolutions/LucataGraphBLAS/issues/294) on LucataGraphBLAS.

**Comment by jamesETsmith** [comment]
@moonwatcher is this urgent or just a bookkeeping issue for down the road?

**Comment by moonwatcher** [comment]
book keeping :) I will bump this ticket when I get around to going the LGB one and you can copy off from there :)
